# Generated by Django 3.0.5 on 2020-05-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('Locality', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('name_suf', models.CharField(default='', max_length=50)),
                ('name_phn', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
